<?php


namespace Admin\Service;

use Admin\Entity\Usuario;
use Core\Entity\AbstractEntity;
use Core\Exceptions\UniqueExcecption;
use Core\Service\AbstractEnityService;

class UsuarioService extends AbstractEnityService
{

    public function create($data, AbstractEntity $entity)
    {
        if(!empty($data['login'])) {
         $user =    $this->getEm()->find(Usuario::class, $data['login']);

         if($user)
             throw  new UniqueExcecption("O usuário já esta cadastrado");
        }
        return parent::create($data, $entity); // TODO: Change the autogenerated stub
    }
}
