<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/auth'));
$form->prepare();


?>
<div class="jumbotron" style="width: 30%; margin-left: 50%; left: -15%; position: relative">
    <h3>Autenticação</h3>
    <?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <?php echo $this->formRow($form->get('username')); ?>
    </div>
    <div class="row">
        <?php echo $this->formRow($form->get('password')); ?>
    </div>

    <div class="row">
        <?php echo $this->formRow($form->get('submit')); ?>
        <!--<?php echo $this->formRow($form->get('newpassword')); ?> -->
    </div>
    <input type="hidden" name="rememberme" value="0">
    <?php echo $this->form()->closeTag(); ?>
</div>
